parse "unbalanced" right square bracket as a literal character
ridiculousfish/regress pull request #50
Opened 2022-10-08 12:42 UTC by selfisekai

I ran into a related issue in boa_engine: https://github.com/boa-dev/boa/issues/2325

I have no idea how to read the ECMAScript documentation, but the introduced behavior is the behavior of regex engines in V8 and SpiderMonkey.

while this commit doesn't seem to fix it in Boa, I believe this change is needed anyway.

2022-10-08 17:39 UTC, ridiculousfish commented
This is yet another difference between non-Unicode (default) and Unicode (u flag) regular expressions. That is in JS `/]/` is valid but `/]/u` is not.

Regress only implements Unicode regexes (for now), because the non-Unicode semantics only make sense in UCS-2. We've thought about implementing non-Unicode semantics; the annoying part is its treatement of surrogate pairs. That said if we could start implementing non-Unicoode behind a flag; or we could just add this and live with the slight divergence from the spec.

Knowing that how do you want to proceed?

2022-10-08 21:22 UTC, selfisekai commented
hm, this is gonna stop breaking my code when YouTube deploys a new JS player version, which I'm guesstimating to Monday in US hours, so I'm fine with an actual non-Unicode implementation

2022-10-09 00:02 UTC, ridiculousfish commented
Ok, if you want to [add a flag](https://github.com/ridiculousfish/regress/blob/f092cf83b89ba4cea9eb213b39b9328bb5b6f21b/src/api.rs#L27) to get started with non-Unicode syntax I'd be happy to merge this.

2022-10-09 00:03 UTC, ridiculousfish requested changes
This change should be controlled by a regress flag to go into non-Unicode parsing mode

2022-10-12 14:49 UTC, selfisekai commented
done now, sorry it took so long

2022-10-14 02:22 UTC, merged

2022-10-14 02:22 UTC, ridiculousfish commented
Hah, I'd forgotten we already had such a flag. Some day we'll have to deal with the real incompatibilities but for now this is fine. Thank you!

2022-10-14 09:09 UTC, selfisekai commented
unrelated - can I also get a `hacktoberfest-accepted` label? 👉👈

2022-10-14 18:59 UTC, ridiculousfish commented
Sure, did I do that right?

2022-10-14 21:40 UTC, selfisekai commented
yes, thank you!