Fix valid character sets in Annex-B
ridiculousfish/regress pull request #62
Opened 2023-04-23 14:50 UTC by HalidOdat

This adds the `"annex-b"` which enables [EcmaScript's Annex-B RegExp syntax](https://tc39.es/ecma262/#sec-regular-expressions-patterns).

Regexes like `[a-\s]` and `[--\d]` are allowed in Annex-b and are not treated like a range, but with mach any char rule. This only applies in non-unicode mode.

2023-04-24 05:44 UTC, ridiculousfish commented
Thank you for this, the code changes look good. `regress` just considers Annex B to be active 100% of the time: literally nobody implements the non-Unicode ES spec without Annex B. Please remove the annex-b feature, treat it as true everywhere and I'll be happy to merge.

2023-04-24 05:45 UTC, ridiculousfish requested changes
^

2023-04-25 04:10 UTC, merged

2023-04-25 04:10 UTC, ridiculousfish commented
Merged as dcc8ab63c8d7234e1a84ee63fc84309a5cc2e6fa, thank you!!

2023-04-25 05:34 UTC, HalidOdat commented
Would it be possible to publish a new version ?

2023-04-28 20:33 UTC, ridiculousfish commented
done, v0.6.0